--CRIA BANCO DE DADOS (DDL)
CREATE DATABASE BancoTarde;

CREATE TABLE Func 
(
IdFunc INT PRIMARY KEY IDENTITY,
Nome VARCHAR(100)
);

CREATE TABLE Empresas 
(
IdEmpresas INT PRIMARY KEY IDENTITY,
IdFunc INT FOREIGN KEY REFERENCES Func(IdFunc),
Nome VARCHAR(100)
);

ALTER TABLE Func
ADD CPF VARCHAR(11)

ALTER TABLE Func
DROP COLUMN CPF

DROP TABLE Empresas; 

DROP DATABASE BancoTarde;
